### ISSUE TITLE
initColorIt() returns error

### ISSUE THREAD

**Issue by ChemGuy88** [CodeForeverAndEver/colorit#1]
Hello,

On mac OS I run

```
from colorit import *

initColorIt()
```

and it returns

```
sh: cls: command not found
```

Does your module support use on mac OS?

Thanks

**Comment by SuperMaZingCoder** [comment]
@ChemGuy88 Ah, let me work on that, I will have fixed that by tomorrow.

**Comment by SuperMaZingCoder** [comment]
One more thing, despite the fact that you get that text, are colors actually being printed? Or does it not let you use your program at all? I believe `ColorIt` may still work. But, I'll work on removing that error.

**Comment by CodeForeverAndEver** [comment]
Actually, I'll just work on it now.

**Comment by CodeForeverAndEver** [comment]
Is there a full error?

**Comment by SuperMaZingCoder** [comment]
Alright, I believe I fixed it. Let me implement it.

**Comment by SuperMaZingCoder** [comment]
Alright @ChemGuy88, I think I have fixed the error. Here is a link to the experimental branch, if you confirm that that updated version works, I will merge it. Just replace whatever file you have for `ColorIt.py` with the file in that branch. That should fix it, if it does, let me know.

Link: https://github.com/CodeForeverAndEver/ColorIt/tree/clear-terminal-error

**Comment by SuperMaZingCoder** [comment]
Alright, no need, I had some others test it, and it is all working good. You can just get it from https://github.com/CodeForeverAndEver/ColorIt now.
