### ISSUE TITLE
Typo in colorit.py

### ISSUE THREAD

**Issue by thmsklngr** [CodeForeverAndEver/colorit#2]
Hi,

noticed a typo in colorit.py, `init_coloit()` instead of `init_colorit()`.

Regards, Thomas

**Comment by SuperMaZingCoder** [comment]
Hey, there, thanks! I must have messed that up yesterday when reformatting the code to be pep-8 compliant.

**Comment by SuperMaZingCoder** [comment]
Fixed: https://github.com/CodeForeverAndEver/ColorIt/commit/6f275d0ee2d8946fbda9dd8af13a213bf377fb3a#diff-47e893b60e0648c40f284662b36626d2
